### ISSUE TITLE
 ERROR - __init__ - Parameter for JSON filename is missing

### ISSUE THREAD

**Issue by LarsDepuydt** [CTHRU/Hitrava#14] opened 2020-06-23 18:10 UTC
I dit everything as prescribed, but still got this error (and a couple more because of this one). 

Do you have any idea how this could be fixed?

Thanks in advance

![Aantekening 2020-06-23 201001](https://user-images.githubusercontent.com/47790106/85439665-8daa8400-b58d-11ea-9459-82cf6b8a06c9.png)

**Comment by CTHRU** [comment] 2020-06-23 19:54
Not sure, but seems related to an issue with extracting the JSON file containing the activity data in the HiZip file.

Could you take a look at the closed issue #9 and check whether your HiZip.zip file contains a valid JSON file?

If this looks OK, you could help me by (temporarily) posting your HiZip.zip file in a comment (if you're OK with that), so I can debug.

If you notice something else, just let me know. We'll get this working.

**Comment by CTHRU** [comment] 2020-06-28 15:18
I didn't hear back from you in the last % days. I assume and I hope you found what was causing the issue.
I will close the issue for now. If the problem wouldn't be solved in the meantime, just reopen this issue.

**Closed by CTHRU** 2020-06-28 15:18 UTC

**Comment by CTHRU** [comment] 2020-08-19 12:57
@LarsDepuydt This is probably a duplicate of #23. Probable cause could be your ZIP file being named 'HiZip.zip.zip' (if your Windows Explorer is set to not display known file extensions.
